### ISSUE TITLE
Please consider moving some tools to Processing

### ISSUE THREAD

**Issue by pcav** [rolandhill/geoscience#1]
This plugin appears a mix of very specific geological tools and very generic ones. It would be very good if you could move the generic ones to main Processing, so they could profit from more contributions and would become useful for more users.
Thanks.

**Comment by rolandhill** [comment]
Thanks, Paulo. I'll take a look at it.
Cheers,
Roland

**Comment by pcav** [comment]
In case of doubt, please refer to qgis-dev mailing list.
Thanks for sharing.
