### ISSUE TITLE
Geoscience stopped working and won't load after re-install

### ISSUE THREAD

**Issue by OzDirtMiner** [rolandhill/geoscience#12]
I am currently using QGIS 3.24.2 and Geoscience has been problematic i.e. not consistent and has now stopped working. I have reinstalled three times and get the error below when trying to load/start Geoscience.

Couldn't load plugin 'geoscience' due to an error when calling its classFactory() method 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\__init__.py", line 36, in classFactory
    return Geoscience(iface)
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\geoscience.py", line 52, in __init__
    self.drillManager = DrillManager()
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 66, in __init__
    self.readProjectData()
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 1110, in readProjectData
    self.sectionManager.readProjectData()
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionManager.py", line 703, in readProjectData
    self.createSection(name, startx, starty, endx, endy, width, layerList, elevationList, False)
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionManager.py", line 502, in createSection
    layer = self.sectionPlaLayer()
  File "C:\Users/Main/ApData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionManager.py", line 527, in sectionPlanLayer
    layer = self.createSectionPlanLayer()
  File "C:\Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionManager.py", line 626, in createSectionPlanLayer
    crs = self.sectionReg[0].sourceLayers[0].crs()
IndexError: list index out of range

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.2-Tisler Tisler, 13c1a028 

Python Path:
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.24.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Main/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Main\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
E:/Dropbox/GIS Projects

**Comment by rolandhill** [comment]
This indicates that Geoscience is trying to load a section that no longer
exists. This usually happens when a section is deleted manually instead of
via the DrillManager.

Try starting QGIS then clicking the New Project icon instead of opening
your project. That will at least show if it's a plugin problem or a project
file problem.

I'm also using 3.24.2 and it haven't had a problem. I'm not developing
Geoscience any more because Oslandia has funding to develop a similar
plugin. I might need to look at a fix for this problem though as it's not
the first time it's happened.

Regards,
Roland

**Comment by OzDirtMiner** [comment]
Thanks Rolland,

Yes it loads in a new blank project just fine. 

 

How do I fix the deleted section issue in my current project as I did manually delete some sections?

 

I am also getting a vector too long error on one section I am trying to load

 

Jeff

**Comment by rolandhill** [comment]
Hi Jeff,

It's a bit hard to fix without a problem dataset here. I've put a guard in
to prevent section creation if the name is empty or there are no layers,
which might stop the crash and give you back access to valid sections.

Give the attached updated version a try and let me know if it helps. Go to
Manage and Install Plugins, then choose Install from Zip on the side.

Regards,
Roland

**Comment by OzDirtMiner** [comment]
Thanks Rolland,

No attachment though.

 

Jeff

**Comment by rolandhill** [comment]
Trying again

**Comment by OzDirtMiner** [comment]
Still no attachment I’m afraid, I will try a new project with just the data I want to put into a section and see how that goes.

 

What is Oslandia’s plugin called do you know and what sort of timeline are they looking at?

 

Jeff

**Comment by rolandhill** [comment]
Hi Jeff,

The attachment was a zip file, so might have been stripped by your email
provider. All those changes are in the latest version now, so just update
via the plugin manager.

The Oslandia product is called OpenLog I think. I'm interested to know how
you go with it if you decide to try it.

Regards,
Roland

**Comment by rolandhill** [comment]
Hi Jeff,

Did you send me an email yesterday? I received one, but I suspect Github
has been reposting old messages. Just saw someone else make the same
observation.

Regards,
Roland

**Comment by OzDirtMiner** [comment]
No I didn't. Sent from my Galaxy
-------- Original message --------From: Roland Hill ***@***.***> Date: 12/10/22  08:09  (GMT+10:00) To: rolandhill/geoscience ***@***.***> Cc: OzDirtMiner ***@***.***>, Author ***@***.***> Subject: Re: [rolandhill/geoscience] Geoscience stopped working and won't load after re-install (Issue #12) 

Hi Jeff,



Did you send me an email yesterday? I received one, but I suspect Github

has been reposting old messages. Just saw someone else make the same

observation.



Regards,

Roland
