### ISSUE TITLE
wrapped C/C++ object of type QgsLayerTreeGroup has been deleted

### ISSUE THREAD

**Issue by sinki-blau** [rolandhill/geoscience#13]
When i'm trying to run the section manager tool, the below error shows up - 
------------------------------------------------------------------------------------------------
2022-08-24T11:48:42     WARNING    Traceback (most recent call last):
              File "~/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionMapTool.py", line 66, in canvasReleaseEvent
              self.sectionManagerDlg.sectionManager.showSection(s)
              File "~AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\SectionManager.py", line 572, in showSection
              s.group.setItemVisibilityChecked( False )
             RuntimeError: wrapped C/C++ object of type QgsLayerTreeGroup has been deleted
--------------------------------------------------------------------------------------------------

Is there anywone who encountered a similar problem and how could it be solved? thanks!

**Comment by rolandhill** [comment]
It is trying to set one of the groups that Geoscience creates to be
visible, but the group has been deleted. Did you delete an ygroups
manually? You should use the Section Manager to delete sections. If you
restart QGIS then you should be able to use the plugin again.

Regards,
Roland
