### ISSUE TITLE
Local Grid: Having error AttributeError: type object 'QgsCoordinateReferenceSystem' has no attribute 'WktVariant' 

### ISSUE THREAD

**Issue by jfpalomeque** [rolandhill/geoscience#14]
Hi,
I am trying to use Local Grid, to transform some local coordinates into wgs 84, but whatever the projected CRS I am choosing, I am having an error: AttributeError: type object 'QgsCoordinateReferenceSystem' has no attribute 'WktVariant'

**Comment by jfpalomeque** [comment]
Hi Roland,
Thank you so much for answering so fast.
I think I can attach the screenshots. I have tried a bunch of projected crs, like EPSG:32420, EPSG:32230 and EPSG:28355 (I tried the last one, even when the coordinates are in the UK, because I saw was used on your website.
And I am always having the same error. 
I am using Qgis 3.8.3-Zanzibar.
Thank you so much again

![image](https://user-images.githubusercontent.com/7852637/223519388-d953ce7b-e2f9-4303-b899-0f9dfba63496.png)
![image](https://user-images.githubusercontent.com/7852637/223519446-3d764d36-a529-4b11-97fd-3a9dd3141964.png)

**Comment by rolandhill** [comment]
Hi Juan,

From the screen shot it looks like you are trying to put latitude and
longitude in where they should be UTM coordinates. Most UTM have 6 digits
for the easting and 7 for the northing.

Regards,
Roland

**Comment by jfpalomeque** [comment]
Hi Roland,

I have converted the coordinates to UTM, and I am having the same error.

Could be an issue with my QGis installation?

Thankn you so much!

![image](https://user-images.githubusercontent.com/7852637/223703220-c08e59ac-e2ed-4d07-ba32-497ea8763126.png)
![image](https://user-images.githubusercontent.com/7852637/223703381-d865a962-c0c5-472f-810c-69216ec5fa44.png)

![image](https://user-images.githubusercontent.com/7852637/223703287-4a7f69c5-5935-4b2d-adaa-ee880151ad24.png)

**Comment by rolandhill** [comment]
Hi Juan,

It is possible that something has changed in the QGIS API. I'm travelling
now, so will need to look at it when I get home. Remind me next week if I
don't get back to you.

Regards,
Roland
