### ISSUE TITLE
Desurvey Issue

### ISSUE THREAD

**Issue by Joaombpaulino** [rolandhill/geoscience#18]
I find problem while trying to use drilling desurvey hole command. this message appear : The data source for the layer could not be found. I tried with your files and it works but it doesn't work with my data!! is there any explanation to that? For information, I use meter unit for parameters such as elevation, depth...

**Comment by rolandhill** [comment]
Are you trying to use data from a network drive? Some people have reported
problems with that. Try it with all the files on a local drive.

If that doesn't work, then you can send your files to me and I can try them
here.

Regards,
Roland

**Comment by Joaombpaulino** [comment]
Hello Roland, thank you for responding.

I am still actively searching for alternatives to solve my problem, but I haven't had any success yet. In fact, I asked a friend to test it out, and they encountered the same issue. In both cases, the files were not saved in the cloud.

The file I am working with is sensitive, so I am not authorized to provide it. However, even when using the materials provided in this video presentation, I encountered an error.

In the video description, it is possible to download the files.

Note: The person in the video was using version 1.5 of Geoscience. I also tried using the same version, but the error persists.

Regards,
João

**Comment by rolandhill** [comment]
Hi Joao,

The other thing to check is for non-english characters in the file and path
names. These have been known to cause problems in the past. As a test, you
could try very simple names eg. collar.csv, survey.csv, assay.csv.

Regards,
Roland
