### ISSUE TITLE
Missing features in downhole data layer

### ISSUE THREAD

**Issue by lauralocasia** [rolandhill/geoscience#19]
Hi there!

I am using the Geoscience plugin to display some drillhole data in QGIS. I keep encountering an issue with my data where some features do not appear in the attribute table of the Downhole data layer, though they are present in the lithology table that they are derived from. I have had this issue with several features, some of which have resolved on their own with time and repeated regeneration of the file, however, there are still a few features missing. (5 overall not generated, the lithology table contains 104 featured and the Downhole data layer contains 99 features... Is there a limit of features for the Downhole Data layer?

For example:
These are some of the features of interest in the Lithology table that's been imported using the Deliminited Text tool:
![image](https://github.com/user-attachments/assets/c288f2df-6089-42c8-8302-8c2c45ee1060)

These are the features that are generated in the Downhole Data layer (bedrock unit of MW24-09S not generated)
![image](https://github.com/user-attachments/assets/d8d1f0bc-5bf5-4dd5-b0e4-984fd8403e18)

I am relatively new to using this plugin, so I am not too familiar with troubleshooting it. Please let me know if you have any advice!

**Comment by rolandhill** [comment]
Hi,

There is no limit on the number of features that get placed in the downhole
tables. The only reason for a feature not to be in there is that there is
no matching drill collar. My guess is that there is no collar for holes
MW24-08D or MW24-10S. Check that they are in your collar file, spelled the
same and capitalised the same. Both those holes use a zero, so also check
that a letter O hasn't been used by mistake.

Regards,
Roland

**Comment by lauralocasia** [comment]
There are collars for all features, I have gone back to double check. No collar/drillhole is entirely missing, just some of the features/sections of lithology within them are. The collars all show up fine as well.

For example, MW24-08S has 6 associated features in the lithology table:
![image](https://github.com/user-attachments/assets/ab0cf6f2-59d4-4cc4-9c2f-ba125c80c76e)
But only 4 of them are generated in the Downhole Data layer.
![image](https://github.com/user-attachments/assets/4ac364dd-3bc2-4527-9d07-b3881c5c8a18)

In addition, as stated, MW24-09S contains 2 lithological units, but only the 1 upper unit is generated in the downhole data layer
![image](https://github.com/user-attachments/assets/8788ac22-8157-42f2-bac1-233011a4aab9)
![image](https://github.com/user-attachments/assets/21c7b9bb-e998-49eb-836b-b2e274492798)

Thank you for the help!

**Comment by rolandhill** [comment]
Can you please send the collar, survey and lithology files to me? I need to
be able to replicate the problem here to figure it out. You can send them
directly to roleyhill @ gmail.com.

Cheers,
Roland

**Comment by lauralocasia** [comment]
Will do, thank you so mcuh!
