### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by cesarcorreo** [rolandhill/geoscience#2]
I'm trying to use the pluging. First I tried to use with my own boreholes with no results, then i tried to use with test data but no results. There is no advance and the program stops in "build Collar Array"
![image](https://user-images.githubusercontent.com/25932761/45740586-dfbeb880-bbf5-11e8-980c-218b546671e8.png)

**Comment by rolandhill** [comment]
Hi cesarcorreo,
I've retested the plugin using the version pulled from the plugin repository and with the test data. It's working here. What QGIS version and operating system are you using?
Roland

**Comment by cesarcorreo** [comment]
Tested again with successful results ¡¡¡¡¡
Excited and waiting for new improvements (drill editable ??? sections, borehole columns ????)
Thanks for your work 
 
![image](https://user-images.githubusercontent.com/25932761/45824105-7d49e300-bcef-11e8-930d-150d05191ab0.png)

**Comment by rolandhill** [comment]
That's great! Thanks for trying it out and for your feedback.
Roland

**Comment by rolandhill** [comment]
Hi Cesar,

Things have been extremely busy at work in the last few weeks and I just
haven't had any time to progress the Geoscience plugin. Hopefully I'll be
able to do some more in the next weeks.

Regards,
Roland

**Comment by cesarcorreo** [comment]
Thanks Roland for the last update.
I will check it tomorrow ¡¡¡¡¡
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*
