### ISSUE TITLE
Can't load plugin in 3.2.3 on Windows

### ISSUE THREAD

**Issue by AlisterH** [rolandhill/geoscience#3]
````
Couldn't load plugin 'geoscience' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\__init__.py", line 36, in classFactory
    return Geoscience(iface)
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\geoscience.py", line 40, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

**Comment by rolandhill** [comment]
Hi Alister,

I just installed 3.2.3 under Windows 10 and it is working here. The line in the error message is reading the locale. Can you please tell me what locale you are using? It's under Settings->Options->Advanced->locale->userLocale. Mine is en_Au
Thanks,
Roland

![image](https://user-images.githubusercontent.com/2024003/46515735-f24d1900-c8a8-11e8-986f-e7081c7c3d05.png)

**Comment by AlisterH** [comment]
en_NZ, 
I see that it does load successfully today, interestingly.

Trying to figure out more about what might have been the problem:
- if I try to change the locale in those advanced options then unload and reload the plugin it fails, and won't load until I restart QGIS.  But changing the locale that way fails itself (when I restart QGIS the locale hasn't changed).
- if I change the locale from the General tab then unload and reload the plugin it doesn't fail.  And then when I restart QGIS the locale has actually changed.  If I then try to change the locale in the advanced options unloading and reloading the plugin _doesn't_ fail.

I certainly hadn't overridden the local myself the other day.  So maybe it also won't load after first being installed without restarting QGIS.  Or maybe some other plugin had overridden my locale (seems unlikely though).

**Comment by rolandhill** [comment]
The code with the error is straight from the plugin template and this has only affected 1 installation. I'll re-open if there are other reports.
