### ISSUE TITLE
survey/DH data import

### ISSUE THREAD

**Issue by ddaearegydd** [rolandhill/geoscience#4]
Hi! Plugin looks super useful, but not clear how to incorporate survey or other downhole data. Projecting Desurvey trace works fine. But "Survey Layer" dropdown under Drilling Data is always empty, as are all dropdowns on "Display Trace". No option to select  Have tried importing CSVs with collar and downhole data, but dropdowns always remain blank. Unsure of what I am doing wrong?

**Comment by rolandhill** [comment]
Hi,

There is a help menu with instructions how to display downhole data. If it still isn’t working then it might be a problem with data types. It assumes the collar will be string and all other numeric values are doubles (decimal)(I need to fix this assumption). You can edit the first line of your data in each file to force this if you have integers. Another thing to try is that you opened the survey and down hole csv files with no geometry. 

If you have no luck then you are welcome to send your files to me. 

Regards 
Roland

**Comment by ddaearegydd** [comment]
Ha, figured it out, yes I don't think it was happy with my formatting. The next problem is weeding out all the dodgy survey traces from the magnetic rocks... Thanks!

**Comment by wissembahri** [comment]
Hello, 
I got the same problem.
How to fix please ?

**Comment by jumbardo** [comment]
Are you importing .csv files with the import tool or just dragging and dropping? Make sure to do the former.

**Comment by rolandhill** [comment]
I always open them with the csv importer. Drill hole names should be strings and coordinates should be doubles.

**Comment by rolandhill** [comment]
I've just uploaded version 0.7 which tries to enforce the correct data types for HoleID, collar coordinates, survey data and downhole distances. Give this a try (when it gets approved) if you are still having problems.

Roland

**Comment by arifdefri** [comment]
hi roland, 
i had a problem whem creating 'download hole'. after collar as points is succesful, i made download hole, but only one point relate to only 7 data of one point. is there any suggestion to solve for another data. 
i have 8 points of hole and 184 row of lithology data. 
thanks

**Comment by rolandhill** [comment]
Hi,

It sounds like a file format problem. You need to have the collar, survey,
lith and assay data in the right format. The plugin has a testdata
directory with examples of the file format. They are attached here for
convenience.

Regards,
Roland
