### ISSUE TITLE
Z-Dimension

### ISSUE THREAD

**Issue by jumbardo** [rolandhill/geoscience#5]
Have you considered having the desurveyed polylines contain the z-dimension? QGIS has some 3d functionality, but you could also export a format like .dxf and bring it into paraview or another 3d viewer. I haven't seen any freeware that desurveys and allows for viewing of drillholes in 3D and you are most of the way there.
Great work btw!

**Comment by rolandhill** [comment]
Hi,

The desurveyed 3D From and To coordinates are appended as columns when you plot down hole data. Also, when you desurvey each drill hole is represented by a poly line with true 3D coordinates. Qgis only pays attention to x & y. It should all be ready for display in 3D. 

Cheers,
Roland

**Comment by rolandhill** [comment]
..... open the attributes of a down hole data plot to see the desurveyed coordinates.

**Comment by jumbardo** [comment]
Thanks very much for the reply. I suspected and still suspect I am doing something incorrectly with data types as my downhole traces show from x from y  to x to y coordinates but the from z and to z coordinates are empty and in 3d view or when exporting to dxf with z values I am still only seeing 2d. Perhaps I can try loading into arcscence but I think my layer in qgis itself is 2d.
![image](https://user-images.githubusercontent.com/43358720/54496552-06209080-48c7-11e9-8999-4bd73aa8ea1a.png)

**Comment by rolandhill** [comment]
Those columns should be filled. Check the data for your collar x, y & z coordinates to make sure they’re valid and that they are float or double. If they are integer then add some .0 to you’re source data. I’ll fix it one day to force the correct types. 
If you don’t have any luck then you can send me your files to check.

**Comment by rolandhill** [comment]
The end of the downhole file should look like the one below. I've just updated the git repository with an update to force the hole id to be a string and the collar coordinates, survey  data and downhole distances to be numbers. Look for an updated version in the QGIS repo soon.

![image](https://user-images.githubusercontent.com/2024003/54714167-02a43800-4b59-11e9-842c-3e6decdfaccc.png)

**Comment by jumbardo** [comment]
Thanks for your hard work. I'll give this a shot later.

**Comment by jumbardo** [comment]
Excellent! The new version is working for me. I threw in the original dataset I had that wasn't super cleaned up and it handled some errors like missing data as well.
![image](https://user-images.githubusercontent.com/43358720/54865264-49508880-4d39-11e9-9c01-ea18d2968058.png)

I've yet to get a 3d view going but it looks like all the data is there.

**Comment by jumbardo** [comment]
Here's the 3d in paraview. I used qgis with grass and used the grass v.out.vtk tool in the processing toolbox.
Now I just need to classify by category somehow, and label by holeID. I'm not sure how to do the second part if it's not part of the attribute table. I might be able to do a join in qgis for the uppormost linestring to the collar point but the rest of the line I'm not sure if it's possible. I'd at least have the top of the hole labeled with a spatial join.
![image](https://user-images.githubusercontent.com/43358720/54867407-3b5d3080-4d56-11e9-9204-1a5e65a05adc.png)
