### ISSUE TITLE
cannot load plugin geoscience when calling its classFactory() method

### ISSUE THREAD

**Issue by davidadbo** [rolandhill/geoscience#7]
Cannot load plugin 'geoscience' due to an error when calling its classFactory() method 

I am using QGIS 3.8 but also confirmed on 3.4. Have removed the geoscience folder under python directory and re-installed.  Have removed all layers created by the plugin in the active QGIS project and re-installed. None of these attempts rectified the issue.

Here's the error message:

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\__init__.py", line 36, in classFactory
    return Geoscience(iface)
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\geoscience.py", line 51, in __init__
    self.drillManager = DrillManager()
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\DrillManager.py", line 65, in __init__
    self.readProjectData()
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\DrillManager.py", line 774, in readProjectData
    self.sectionManager.readProjectData()
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\SectionManager.py", line 686, in readProjectData
    self.createSection(name, startx, starty, endx, endy, width, layerList, elevationList, False)
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\SectionManager.py", line 485, in createSection
    layer = self.sectionPlanLayer()
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\SectionManager.py", line 510, in sectionPlanLayer
    layer = self.createSectionPlanLayer()
  File "C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\DWA/python/plugins\geoscience\SectionManager.py", line 609, in createSectionPlanLayer
    crs = self.sectionReg[0].sourceLayers[0].crs()
IndexError: list index out of range

Thank you for your help.

**Comment by rolandhill** [comment]
Hi David,

It looks like the plugin is trying to load sections from your QGIS Project
file that don't exist. I'm not sure how that has happened. To recover the
project and get Geoscience to load again you will need to tell it that
there are no sections (or the correct number of sections) to load. You will
need to edit the qgs project file. Look for "<Sections " and change it to
0.
[image: image.png]

If you see real sections in the project (denoted by the prefix S00, S01
etc) then you can set it to the correct number (eg 1 if you have S00, 2 if
you have S00 & S01).

[image: image.png]

If your project is a qgz, then it is just a zipped qgs. Simply unzip it,
edit it then re-zip.

I'll change the code so it doesn't crash if this happens in the future.
Thanks for the report.

Regards,
Roland

**Comment by davidadbo** [comment]
Hi Roland,

 

Thank you for your reply. It looks like there may have been images in your email but these did not show up. However, I tried to follow the text instructions.

 

I believe I removed sections in the active project several times through a process of trial and error in testing the plugin (which is useful by the way!) . Here’s what I did:

 

1.	I searched the qgs version of the file for the string “Sections “ and found:

 

<Sections type="int">2</Sections> (I tried 0 and 2, originally it had 1 in the file)

 

2.	I searched for S00 (and S01 etc) and find two mentions of S00 but these are obviously two different sections:

 

<S00_ElevationLayer00 type="QString">cxq_100</S00_ElevationLayer00>

      <S00_ElevationLayers type="int">1</S00_ElevationLayers>

      <S00_EndX type="int">581306</S00_EndX>

      <S00_EndY type="int">6998304</S00_EndY>

      <S00_Name type="QString">581149E</S00_Name>

      <S00_SourceLayer00 type="QString">CollarV1_Corrected_3D</S00_SourceLayer00>

      <S00_SourceLayer01 type="QString">CollarV1_Corrected_Desurvey</S00_SourceLayer01>

      <S00_SourceLayers type="int">2</S00_SourceLayers>

      <S00_StartX type="int">580991</S00_StartX>

      <S00_StartY type="int">6997776</S00_StartY>

      <S00_Width type="int">50</S00_Width>

      <SectionEast type="int">0</SectionEast>

      <SectionLimitEast type="int">1</SectionLimitEast>

      <SectionLimitNorth type="int">1</SectionLimitNorth>

      <SectionLimitSouth type="int">0</SectionLimitSouth>

      <SectionLimitWest type="int">0</SectionLimitWest>

      <SectionName type="QString">581149E</SectionName>

      <SectionNorth type="int">0</SectionNorth>

      <SectionSNName type="QString"></SectionSNName>

      <SectionStep type="int">50</SectionStep>

      <SectionWEName type="QString"></SectionWEName>

      <SectionWidth type="int">50</SectionWidth>

      <Sections type="int">2</Sections>

 

So it looks like I have managed to create a bit of a mess. Any suggestions?

 

Thanks again.

 

David
