### ISSUE TITLE
Python error when accessing log file

### ISSUE THREAD

**Issue by MarrinerJustin** [rolandhill/geoscience#8]
I'm encountering a Python error when attempting to desurvey the sample borehole data provided with the QGIS plugin. Copied below.

The error occurs even if I manually create the Geoscience_DrillManager_log.txt file myself. It occurs whether the data is on my internal hard drive or external USB drive.

I'm using QGIS 3.10 on a mac running Catalina 10.15.1.

Much appreciated if you can suggest a solution.

`2019-12-02T15:47:31     WARNING    Traceback (most recent call last):
              File "/Users/justin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoscience/DrillManager.py", line 114, in onDesurveyHole
              self.openLogFile()
              File "/Users/justin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoscience/DrillManager.py", line 76, in openLogFile
              self.logFile = open(os.path.join(os.path.dirname(fileName), "Geoscience_DrillManager_log.txt"),'w')
             FileNotFoundError: [Errno 2] No such file or directory: 'file:/Volumes/USBdrive/Borehole data/Geoscience_DrillManager_log.txt'`

**Comment by rolandhill** [comment]
Hi Justin,

There was an issue with creating the log file name in the correct format on
Mac. I've just pushed a fix to the plugins repository. Look for version 1.1
when it gets approval.

I don't have a Mac to test it on. Can you please get back to me to confirm
it works.

Regards,
Roland

**Comment by Janiveau** [comment]
Hi Roland,

I am facing a similar issue, if not the same, with the latest version of the geoscience plugin:

_2022-10-06T13:53:03     WARNING    Traceback (most recent call last):
              File "C:\Users/janpl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 114, in onDesurveyHole
              self.openLogFile()
              File "C:\Users/janpl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoscience\DrillManager.py", line 77, in openLogFile
              self.logFile = open(fileName,'w')
             OSError: [Errno 22] Invalid argument: 'file:\\hgserv\\Daten\\Projekte\\Laufende Projekte\\Sylt - D%C3%BCnenpark\\02 GIS\\Geoscience_DrillManager_log.txt'_ 

Has this occurred often, after the thread was closed?

Thanks for any help

Best Regards,
Jan

**Comment by rolandhill** [comment]
Hi Jan,

I haven't had any similar reports. I notice that you have some special characters in the filename within D%C3%BCnenpark

OSError: [Errno 22] Invalid argument: 'file:\hgserv\Daten\Projekte\Laufende Projekte\Sylt - D%C3%BCnenpark\02 GIS\Geoscience_DrillManager_log.txt'

Can you please try processing your drill holes in a directory/path without non-standard english characters. At least this will tell us if that is the problem.

I'll probably just remove all the log file code in the next version. I never got around to making it do what it was supposed to.

Regards,
Roland

**Comment by Janiveau** [comment]
Hi Roland, we were able to solve it. It was a data directory problem. When it says inv. argument: 'file' it is expecting 'C:' . I was utilizing files from a server. now it works, copying the files locally. Thanks for your response.

Regards
Jan
