### ISSUE TITLE
Lithology data not displaying down desurveyed drill trace in "sections"

### ISSUE THREAD

**Issue by rmk206** [rolandhill/geoscience#9]
I added in all my CSV files to qgis, desurved the ddh, and then I added drill hole data to the desurveyed trace (litho), and all of that worked fine. The litho displays as it should down the hole, BUT as soon as I go into section manager and cut a section by "map extent" the lithology no longer appears along the drill hole trace in the section view. Any idea how to make it plot along the trace in section..?

**Comment by rolandhill** [comment]
Hi rmk206,
In Section Manager, click "Map Canvas", draw your section line, then in the subsequent dialog box make sure you have all the layers you want to show in the section selected. This includes the downhole lithology layer that you previously generated. See image below (in this case it's the downhole assay).

Roland

![image](https://user-images.githubusercontent.com/2024003/111085713-a2400980-856c-11eb-8a5d-e3f695df8fbd.png)

**Comment by rmk206** [comment]
Hi Roland,

I had done that, and the litho layer is checked off to be included. But as soon as the section is generated for some reason it does not include the litho data in the section, even though it was checked off.

**Comment by rolandhill** [comment]
It sounds like you've done everything correctly then. Are you able to send me the data to test here?

**Comment by rmk206** [comment]
Hi Roland

Sure thing!
I've attached the data below. Thanks.

Cheers,
Rebecca

**Comment by rmk206** [comment]
Hi Roland,

not sure the data was able to attach, is there an email I can send the .CSV files to?

**Comment by rolandhill** [comment]
Hi Rebecca,

I can't see any attachment and don't know if that works it Github. You can send it directly to 

roleyhill at gmail dot com.

Cheers,
Roland
